### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by mhmxs**
Without these changes installation went fail. Would be nice to merge them, but let me know if you have any objections.

### CODE REVIEW

**Comment by dberuben** [comment]
Nice !

**Comment by mhmxs** [comment]
Sorry, i'm not 100% sure about this commit: https://github.com/pawankkamboj/HA-kubernetes-ansible/pull/13/commits/5c7ea2d6947404b31a52cbf0de9f804e79b53a2d. I tested only with one master node, and was ok, but seems it has (more) issue with multi master setup. I have to do more testing, but come back in a few days.
```
fatal: [192.168.50.12 -> 192.168.50.12]: FAILED! => {"changed": false, "cmd": "/bin/rsync --delay-updates -F --compress --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no' --out-format='<<CHANGED>>%i %n%L' \"/opt/kubernetes/pki\" \"/etc/kubernetes\"", "failed": true, "msg": "rsync: change_dir \"/opt/kubernetes\" failed: No such file or directory (2)\nrsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1052) [sender=3.0.9]\n", "rc": 23}
```

**Comment by mhmxs** [comment]
With the last commit i fixed certification distribution problem.

**Review by pawankkamboj — COMMENTED** [review]
This will work only if there is single node cluster, for multinode you need to add IPs of all your cluster members

**Review by pawankkamboj — CHANGES_REQUESTED** [review]
Please update it to works with multi node cluster

**Review by pawankkamboj — APPROVED** [review]

**Comment by pawankkamboj** [comment]
thanks for suggestion and fixes

**Pull request merged**
